//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_rol
    {
        public int usuario_id { get; set; }
        public int id { get; set; }
        public int id_usuario_rol { get; set; }
    
        public virtual rol rol { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
