//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuarios()
        {
            this.usuario_rol = new HashSet<usuario_rol>();
        }
    
        public int id { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public Nullable<decimal> celular { get; set; }
        public string numero_fijo { get; set; }
        public string clave { get; set; }
        public Nullable<int> documento { get; set; }
        public int id_estados { get; set; }
        public string correo { get; set; }
        public Nullable<int> id_documento { get; set; }
        public Nullable<int> id_curso { get; set; }
    
        public virtual curso curso { get; set; }
        public virtual estados estados { get; set; }
        public virtual novedades novedades { get; set; }
        public virtual tipo_documento tipo_documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario_rol> usuario_rol { get; set; }
    }
}
