//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lack
    {
        public int IdLack { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
        public int IdSubject { get; set; }
        public int JustificationId { get; set; }
    
        public virtual Justification Justification { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
