//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public int IdCourse { get; set; }
        public int IdSubject { get; set; }
        public string IdTeacher { get; set; }
        public int IdDay { get; set; }
        public System.TimeSpan HourFrom { get; set; }
        public System.TimeSpan HourTo { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual Days Days { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
