//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int IdStudent { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public int DocumentTypeId { get; set; }
        public int CourseId { get; set; }
        public string Document { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual DocumentType DocumentType { get; set; }
    }
}
