//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectsByCourse
    {
        public int IdSubjectxCourse { get; set; }
        public int IdSubjects { get; set; }
        public int IdCourse { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
