//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public Courses()
        {
            this.Assistances = new HashSet<Assistances>();
            this.Lacks = new HashSet<Lacks>();
            this.News = new HashSet<News>();
            this.Students = new HashSet<Students>();
        }
    
        public int IdCourse { get; set; }
        public string Description { get; set; }
        public string IdTeacher { get; set; }
        public Nullable<int> TotalStudents { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<Assistances> Assistances { get; set; }
        public virtual ICollection<Lacks> Lacks { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Students> Students { get; set; }
    }
}
