//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Justification
    {
        public Justification()
        {
            this.Lacks = new HashSet<Lacks>();
        }
    
        public int IdJustification { get; set; }
        public string Description { get; set; }
        public byte[] Attached { get; set; }
    
        public virtual ICollection<Lacks> Lacks { get; set; }
    }
}
