//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        public Subjects()
        {
            this.Assistances = new HashSet<Assistances>();
            this.Lacks = new HashSet<Lacks>();
        }
    
        public int IdSubjects { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Assistances> Assistances { get; set; }
        public virtual ICollection<Lacks> Lacks { get; set; }
    }
}
